apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chadgpt.fullname" . }}
data:
  config.yaml: |
    ---
    irc:
      # The hostname or IP address of the IRC server.
      host: irc.rwx.im
      # The port number of the IRC server.
      port: 6697
      # Use a secure connection.
      tls: true
      # The nickname used by the bot.
      nick: chad
      # The username used by the bot.
      username: chad
      # The version response to CTCP VERSION requests.
      version: "github.com/rwx-labs/chadgpt"
      # List of channels to join when initially connected.
      channels:
        - "#uplink"
        - "#chad"
      # List of nicknames to ignore messages from.
      ignored_nicks: []

    # Configuration for the GPT completion requests.
    # Reference: https://beta.openai.com/docs/api-reference/completions
    openai:
      # The identifier of the model to use for completions.
      model: text-davinci-003
      # What sampling temperature to use. Higher values means the model will take
      # more risks.
      temperature: 0.5
      # The maximum number of tokens to generate in the completion.
      max_tokens: 60
      # An alternative to sampling with temperature, called nucleus sampling, where
      # the model considers the results of the tokens with top_p probability mass.
      # So 0.1 means only the tokens comprising the top 10% probability mass are
      # considered.
      top_p: 0.1
      # Number between -2.0 and 2.0. Positive values penalize new tokens based on
      # whether they appear in the text so far, increasing the model's likelihood to
      # talk about new topics.
      presence_penalty: 0.0
      # Number between -2.0 and 2.0. Positive values penalize new tokens based on
      # their existing frequency in the text so far, decreasing the model's
      # likelihood to repeat the same line verbatim.
      frequency_penalty: 0.5
      # The prompt to generate completions for, encoded as a string, templated with Mustache.
      #
      # Available variables:
      # `message` - The message a user sent to the bot (not including the bot nick)
      # `rawMessage` - The message a user sent to the bot, including the bot nick
      # `channel` - The name of the channel the message was sent in.
      # `nick` - The nickname of the sender.
      prompt: |-
        Q: Who is Batman?
        A: Batman is a fictional comic book character.

        Q: What is torsalplexity?
        A: ?

        Q: What is Devz9?
        A: ?

        Q: Who is George Lucas?
        A: George Lucas is American film director and producer famous for creating Star Wars.

        Q: What is the capital of California?
        A: Sacramento.

        Q: What orbits the Earth?
        A: The Moon.

        Q: Who is Fred Rickerson?
        A: ?

        Q: What is an atom?
        A: An atom is a tiny particle that makes up everything.

        Q: Who is Alvan Muntz?
        A: ?

        Q: What is Kozar-09?
        A: ?

        Q: How many moons does Mars have?
        A: Two, Phobos and Deimos.

        Q: {{ `{{ message }}` }}
        A:
