{{- if .Values.turbochad.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chadgpt.fullname" . }}-turbo
  labels:
    {{- include "chadgpt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chadgpt.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.turbochad.yaml") . | sha256sum | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chadgpt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: CONFIG_PATH
          value: /config/config.yaml
        envFrom:
        - secretRef:
            name: chadgpt-env
        volumeMounts:
        - name: config
          mountPath: /config
        args: [-c, /config/config.yaml]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "chadgpt.fullname" . }}-turbo
{{- end }}
