apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: magistr.dk
  labels:
    app.kubernetes.io/instance: magistr
spec:
  commonName: magistr.dk
  dnsNames:
  - "magistr.dk"
  - "*.magistr.dk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: magistr.dk-tls
