---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magistr
spec:
  template:
    spec:
      containers:
      - name: magistr
        env:
        - name: RUST_LOG
          value: "magistr=trace,tower_http=trace,sqlx=trace"
        - name: MAGISTR_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: DATABASE_URL
