---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magistr
spec:
  template:
    spec:
      containers:
      - name: magistr
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres
