images:
- name: ghcr.io/rwx-labs/magistr
  newTag: 0.2.4

namespace: magistr-prod

resources:
- ../../base
- ./middleware.yaml
- ./certificate.yaml
- ./ingressroute.yaml
- ./sealedsecret.postgres.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ./deployment.yaml
