images:
- name: ghcr.io/rwx-labs/magistr
  newTag: sha-b9eb6c398822e5d233425f83debd694a95a29d39

namespace: magistr-prod

resources:
- ../../base
- ./middleware.yaml
- ./certificate.yaml
- ./ingressroute.yaml
- ./sealedsecret.postgres.yaml
patchesStrategicMerge:
- ./deployment.yaml
