images:
- name: ghcr.io/rwx-labs/magistr
  newTag: 0.2.3

namespace: magistr-prod

resources:
- ../../base
- ./middleware.yaml
- ./certificate.yaml
- ./ingressroute.yaml
- ./sealedsecret.postgres.yaml
patchesStrategicMerge:
- ./deployment.yaml
