images:
- name: ghcr.io/rwx-labs/magistr
  newTag: sha-6d87e75ebfb7cd214c9e94b146b758829de02325

namespace: magistr-prod

resources:
- ../../base
- ./middleware.yaml
- ./certificate.yaml
- ./ingressroute.yaml
- ./sealedsecret.postgres.yaml
patchesStrategicMerge:
- ./deployment.yaml
