---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgAjy7l1NBujj5Ce4KDRbqpd6JGuJFJaVvzV29mHQtgfe8jH5U2P8EvgS4xv+yr1d41MjoJ/dIRx2CWDJt5pRoJ6uSFiqokpVqxh6zPfmBY0W78c/ApAEmT6XQJXz6RbSKgpQ/+pzdpQp+OAQQo1HTjl+l2Pif/pFKdLmkvlAzavhoaURvQ3gBhF6pr6jtp0/ZT8+PQa0OOv+oCmJv/YMdZSWZSpmK+w8e0FNmquP/CeF6EHOrMEnwYgElz6X/92a6MzmKNGMdrCUJLk8014hJZLlNMLKTkJvLtriyCbKG1ObZ7Xj6IAqbAiUyAsERffTiUyp0qUMWaliZW/IAgOFSYZS/ImGuWoZN3YSEIX7vlEg6o+3OPHCHegOhS3guYTfo+xfuJhpJMW+qilt2CJhzcGW0DtTJT4bBNQCHMYlzBNsnKxFFvX7oi+AjNm7QCjcGxob+iRXtaqB9VmFapzP8uuZdoxF/VpTH1hRBlyCqtG/f0jrMDOfVoZ786v16guqMDnI8wZ911R7RzsASa2ITmFGw+zW2+ZsVR+UpIdWxmloKb2ynURf43ugxloWo/tn1cHOijP3bL2KepdNJmt65m5eGyuAOMCL8LSYasip1w2EgASP8LjTniXxWb5pfHRmdFCbsFsg9ACu6Dh61ytPk8IcFjSbmRTVIl1ZarrL3cZByxB9fXAqMf0Vw7kHV9KEHUAbU1aR7V+9P7yICY/1NRHk0UeWdUEFtl49B0vuL1DYyvgtXXSgTb0FhRyNlTJrcN35R5UyGwJ/oHToOE9b5YEXruZga9iAaJhOZhYfEEcf2ur86zkaOAUqvHK8dJAdV+RojY=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: default
