apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: magistr-prod
spec:
  encryptedData:
    DATABASE_URL: AgCDrQweAMX8aKts6I+OjAsgIVsufjkHr+4cTGvyZo/Tng1giHysA1rgZLwsoLI108OyWD6HXSjAMlNJ2voMFjeIWuP65tYi5moroprz10VA8w4eRWy5TLJO7ycI0QKktrkXKIWoaXTXVN+Qa0yYSVE9SnhODfktqa23cvTUF59+N5tohCH6JjKNq8NtNes1OEZZb2D9+/Hx2/8Z4TM83/JlUBE598DnM4Md3QGHtLGjOoSubdYCr3XuT6uVQIQaMUamyxjuOm5J5ohBFcxQ1c9YYqf9HUGclOBJ/9OKRTmAdX40OPQIhhY1KdsuVn3/TRyznEQcLpCtzg5a5M/WEVlL/a8/OW0gfL+FgtyMvD8DoB4mTv0zbxIXZ6gdsc0VVHakTG6xgyyKcUac2Qpa1U4BWy53WcZ/WVtUkRKa/NHt7Sk8P1N3uJ41arbeCaI7HDLTKBKRUPNGLqIuJqHLWivSmF1v/wOKuZ3bEnwxWmZQeqdqtF7xUoIgS73Ld03MhMnOe10gPAQJb9ecUu027sDJrcQ/HyIYfk00fqpWZMXM3ozvBIcBKpDFQ+AjfiZa5kcliiBa1NgUI4x6RXd30ubuXRdvn7uvsuj30cNW0HEzT2rjaA+J5rIlN2osPbz6v7DBZsp1/DH+5Wj1jnkUefVssGwm5ImKAHE4VnxakhqKBfeoUx494o/f/UIsH6wD66d0qKCYjpjytoCwCUaulkLF1cnyP0ww/xvcSYzoV5iDO+TH1r2TIzh3ROQOdYwpCmcTz6Kfnu6JZnThQUG7KHzwZvW5YGN/y1rsGgBSHZziA9pDbRjFFyOQDBk9aJZ5T5tHq1g=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: magistr-prod

