apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: magistr-prod
spec:
  encryptedData:
    DATABASE_URL: AgA2uL3pHZ6x2pf1RbID016jY07p37VcQJJmHmIfsAG3C+tuBjozWrtHGDIW0ZCSgJJvqX5x1SZh8NDiD1JmdrvLOBBxM/VMk/DT4YS1RXI4MgEs0Z3DGfDqdeYuwcfR8DcUHP5/cj4LUzw1qum+ltnYaMyF4m1z6eA6CvAaK3Fr2fCT1XgndB7A8Fc4Ut0q2I+kRyVTrZeNtxfwD9PPiWYcQFP5TuBOsCMbAJibc3uRdOuDEngbym919M+JNtqsEtriPSj5pblXulJh/wX98PnqlCa1IQeYfUCgJcx/iz0HyBC5SoqX1BsPQ2clhcW2t2hb9RsrYPI8OzrHVFVefjrHSyMK5VMXmav6brshHmNtO7q8plNJejMRIgPtg2ATdXo17nOHA4Geesn6rKDEvu2MIcMVSB0Jd7ktl4sfF5aPavgjA8Lk8WKGZiL5sN1rt4x/2lQkleUDcKFk4yCnuKdtYQgZCtQlS1OvJZM4E2/kwAkcGl3EL50slJqUpyEYqNdlLKT6X0Enbi8/EmRtyQ2pCCqIQG84gjxGbyNIc+3j0L405aut2CgjPNFsIiPf8Pe63co3Drjy/GbSut4Nlh89kME/QVk42ksCZTmS1q6ZODE/T8er0LZ7nLhuw0uzBt30HjO6z2oAlHVwlsP5Z9mTcGEc9f3ti9SUAlFbgaPNmOLbCrJM4y7KkKy7dGkEqMIIQvISrxzM/PwMb8lS+/j/LYaOTugEJGdaaMvcZxmGULpI6EZh0uNHygIbOlJsGTJ0x7IzdZ6aMxPUp3WFjhqb+Dr7GcXIlKYBIX0gEknJ/eHelhuLrcW+pchCw5rQgqm9vo4=
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: magistr-prod

